---
path_classifiers:
  test:
    - test
    - tests
  docs:
    - doc

extraction:
  python:
    python_setup:
      version: 2
    prepare:
      packages:
        - make
        - g++
        - python3-dev
        - python3-wheel
