no_blank_comment: False # Always comment even if things are OK

scanner:
    linter: flake8
    diff_only: False

flake8:
    max-line-length: 120
    ignore:  # Errors and warnings to ignore
      - E501 # line too long (90 > 79 characters)
      - E303 # too many blank lines (2)
      - E302 # expected 2 blank lines, found 1
      - E261 # at least two spaces before inline comment
      - E265 # block comment should start with '# '

    exclude: []
    count: True
    show-source: True
    statistics: True
