[build-system]
requires = ["setuptools>=51.2", "wheel>=0.36.2", "setuptools_scm[toml]>=6.0.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/decisionengine/framework/version.py"
version_scheme = "post-release"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-l -v --durations=30 --durations-min=0.05 --strict-config --strict-markers"
log_level = "debug"
testpaths = "src/decisionengine"
required_plugins = "pytest-timeout>=1.4.2"
timeout = 90
flake8-max-line-length = "120"
flake8-ignore = "E501 E303 E302 E261 E265 W503 W504"
flake8-show-source = "True"
flake8-statistics = "True"

[tool.black]
line-length = 120
