[build-system]
requires = ["setuptools>=51.2", "wheel>=0.36.2", "setuptools_scm[toml]>=6.0.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/decisionengine/framework/version.py"
version_scheme = "post-release"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-l -v --durations=0"
log_level = "debug"
testpaths = "src/decisionengine"
timeout = 120
flake8-max-line-length = "120"
flake8-ignore = "E501 E303 E302 E261 E265 W503 W504"
flake8-show-source = "True"
flake8-statistics = "True"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120

[tool.coverage.run]
branch = true
concurrency = ["multiprocessing", ]
omit = ["*/tests/*", ]
source = ["src", ]

[tool.coverage.report]
skip_empty = true

# Regexes for lines to exclude from consideration
exclude_lines = [ "pragma: no cover", # Have to re-enable the standard pragma
                  "raise AssertionError",
                  "raise NotImplementedError", # Don't complain if tests don't hit defensive assertion code:
                  "if __name__ == .__main__.:", # Don't complain if non-runnable code isn't run:
 ]
