[build-system]
requires = ["setuptools>=51.2", "wheel", "setuptools_scm[toml]>=6.0.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/decisionengine/framework/version.py"
version_scheme = "post-release"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-l -v --durations=0"
log_level = "debug"
testpaths = "src/decisionengine"
timeout = 120
flake8-max-line-length = "120"
flake8-ignore = "E501 E303 E302 E261 E265 W503 W504"
flake8-show-source = "True"
flake8-statistics = "True"
