ARG BASEIMAGE=${BASEIMAGE:-hepcloud/decision-engine-ci}
FROM ${BASEIMAGE:-hepcloud/decision-engine-ci}
ARG USER
ARG GROUP
COPY entrypoint.sh /entrypoint.sh
RUN groupadd -g ${GROUP:-500} decision-engine-ci
RUN useradd -u ${USER:-500} -g ${GROUP:-500} decision-engine-ci
USER decision-engine-ci
ENTRYPOINT ["/entrypoint.sh"]
