{
 "title": "Channel Data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "channel",
    "label": "Channel",
    "query": {
     "query": "label_values(de_channel_state,channel_name) "
    }
   },
   {
    "name": "transform",
    "label": "Transform",
    "query": {
     "query": "label_values(de_transform_last_run_timestamp_seconds, transform_name)"
    }
   },
   {
    "name": "publisher",
    "label": "Publisher",
    "query": {
     "query": "label_values(de_publisher_last_run_timestamp_seconds, publisher_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transform Collection Time",
   "type": "timeseries",
   "description": "Time series of the transform's duration and instance of data collection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(de_transform_run_seconds_bucket{transform_name=\"$transform\"}[5m])) by (le))",
     "legendFormat": "99Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(de_transform_run_seconds_bucket{transform_name=\"$transform\"}[5m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(rate(de_transform_run_seconds_bucket{transform_name=\"$transform\"}[5m])) by (le)) + histogram_quantile(0.99, sum(rate(de_transform_run_seconds_bucket{transform_name=\"$transform\"}[5m])) by (le))) / 2",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Logic Engine Collection Time",
   "type": "timeseries",
   "description": "Time series of the logic engine's duration and instance of data collection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(de_logicengine_run_seconds_bucket[5m])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(de_logicengine_run_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(rate(de_logicengine_run_seconds_bucket[5m])) by (le)) + histogram_quantile(0.99, sum(rate(de_publisher_run_seconds_bucket[5m])) by (le))) / 2",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Time Transform Last Ran",
   "type": "table",
   "description": "Timestamp for when Transform last ran.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "de_transform_last_run_timestamp_seconds{channel_name=\"$channel\", transform_name=\"$transform\"} * 1000"
    }
   ]
  },
  {
   "title": "Time Logic Engine Last Ran",
   "type": "table",
   "description": "Timestamp for when Logic Engine last ran.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "de_logicengine_last_run_timestamp_seconds{channel_name=\"$channel\"} * 1000"
    }
   ]
  },
  {
   "title": "Publisher Collection Time",
   "type": "timeseries",
   "description": "Time series of the publisher's duration and instance of data collection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(de_publisher_run_seconds_bucket{publisher_name=\"$publisher\"}[5m])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(de_publisher_run_seconds_bucket{publisher_name=\"$publisher\"}[5m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(rate(de_publisher_run_seconds_bucket{publisher_name=\"$publisher\"}[5m])) by (le)) + histogram_quantile(0.99, sum(rate(de_publisher_run_seconds_bucket{publisher_name=\"$publisher\"}[5m])) by (le))) / 2",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Channel State",
   "type": "stat",
   "description": "State of the selected channel.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "de_channel_state{channel_name=\"$channel\"}"
    }
   ]
  },
  {
   "title": "Time Publisher Last Ran",
   "type": "table",
   "description": "Timestamp for when publisher last ran.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "de_publisher_last_run_timestamp_seconds{channel_name=\"$channel\", publisher_name=\"$publisher\"} * 1000"
    }
   ]
  },
  {
   "title": "Channel Startup Time",
   "type": "stat",
   "description": "Number of seconds to launch",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "de_client_start_channel_duration_seconds_sum{channel_name=\"$channel\"}"
    }
   ]
  }
 ]
}