{
 "title": "Source Data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(de_source_last_acquire_timestamp_seconds{job=\"decisionengine-dev-sfoster\"}, source_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Source State",
   "type": "stat",
   "description": "Current status of the source",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "de_source_status{job=\"decisionengine-dev-sfoster\", source_name=\"$source\"}"
    }
   ]
  },
  {
   "title": "Source Collection Time",
   "type": "timeseries",
   "description": "Time series of the source's duration and instance of data collection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(de_source_acquire_seconds_bucket{job=\"decisionengine-dev-sfoster\", source_name=\"$source\"}[5m])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(de_source_acquire_seconds_bucket{job=\"decisionengine-dev-sfoster\", source_name=\"$source\"}[5m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(rate(de_source_acquire_seconds_bucket{job=\"decisionengine-dev-sfoster\", source_name=\"$source\"}[5m])) by (le)) + histogram_quantile(0.50, sum(rate(de_source_acquire_seconds_bucket{job=\"decisionengine-dev-sfoster\", source_name=\"$source\"}[5m])) by (le))) / 2",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Source Count",
   "type": "stat",
   "description": "Numbers of metrics collected of the source",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_count{job=\"decisionengine-dev-sfoster\", source_name=\"$source\"}"
    }
   ]
  },
  {
   "title": "Source Sum",
   "type": "table",
   "description": "Sum of the source's metric collection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max(de_source_acquire_seconds_sum{job=\"decisionengine-dev-sfoster\", source_name=\"$source\"}) by (source_name)"
    }
   ]
  },
  {
   "title": "Time Source Last Ran",
   "type": "table",
   "description": "Timestamp for when source last ran",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(de_source_last_acquire_timestamp_seconds{job=\"decisionengine-dev-sfoster\", source_name=\"$source\"} * 1000) by (source_name)"
    }
   ]
  }
 ]
}