---
name: Test in EL7 container

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '**'          # matches every branch
      - '!gh-pages'   # excludes gh-pages branch

jobs:
  rpm_build_job:
    runs-on: ubuntu-latest
    name: A job to test the decision engine framework on EL7

    steps:
      - name: checkout code tree
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run the tests in a container (SL7/HEPCloud-CI)
        uses: ./.github/actions/pytest-in-sl7-container

      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: test-log
          path: pytest.log
          if-no-files-found: error
