---
name: Build DecisionEngine RPM

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '**'          # matches every branch
      - '!gh-pages'   # excludes gh-pages branch

jobs:
  rpm_build_job:
    runs-on: ubuntu-latest
    name: A job to build the decision engine framework rpm

    steps:
      - name: checkout code tree
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build the RPM in a container (SL7/HEPCloud-CI)
        uses: ./.github/actions/rpmbuild-in-sl7-container

      - name: Archive rpm
        uses: actions/upload-artifact@v2
        with:
          name: rpms
          path: decisionengine/dist/*.rpm
          if-no-files-found: error
